<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Tests for MartinCostello.OpenApi.Extensions.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.Http.Generated;Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
    <IsAotCompatible>false</IsAotCompatible>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <OutputType>Exe</OutputType>
    <RootNamespace>MartinCostello.OpenApi</RootNamespace>
    <TargetFrameworks>net11.0;net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GitHubActionsTestLogger" />
    <PackageReference Include="MartinCostello.Logging.XUnit.v3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\samples\TodoApp\TodoApp.csproj" />
    <ProjectReference Include="..\..\src\OpenApi.Extensions\MartinCostello.OpenApi.Extensions.csproj" />
    <ProjectReference Include="..\Models.A\Models.A.csproj" />
    <ProjectReference Include="..\Models.B\Models.B.csproj" />
    <ProjectReference Include="..\TestApp\TestApp.csproj" />
    <ProjectReference Include="..\WebApi\WebApi.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <CollectCoverage>true</CollectCoverage>
    <CoverageRunSettings>$(MSBuildThisFileDirectory)tests.runsettings</CoverageRunSettings>
    <Threshold>90,75</Threshold>
  </PropertyGroup>
</Project>
