version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
- package-ecosystem: nuget
  directory: "/"
  groups:
    xunit:
      patterns:
        - Verify.Xunit*
        - xunit*
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
  ignore:
    - dependency-name: "Microsoft.AspNetCore.OpenApi"
    - dependency-name: "Microsoft.OpenApi*"
